name: 'nyu_ed_classification'
version: '1.0.0'
config-version: 2
require-dbt-version: ">=1.10.5,<3.0.0"

profile: default

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  tuva_last_run: '{{ run_started_at.astimezone(modules.pytz.timezone("UTC")) }}'

seeds:
  nyu_ed_classification:
    value_sets:
      ed_classification:
        ed_classification__categories:
          +post-hook: "{{ the_tuva_project.load_package_seed('nyu-ed-classification', nyu_ed_classification.get_nyu_ed_classification_package_version(), 'ed_classification__categories.csv.gz') }}"
        ed_classification__icd_10_cm_to_ccs:
          +post-hook: "{{ the_tuva_project.load_package_seed('nyu-ed-classification', nyu_ed_classification.get_nyu_ed_classification_package_version(), 'ed_classification__icd_10_cm_to_ccs.csv.gz') }}"
        ed_classification__johnston_icd10:
          +post-hook: "{{ the_tuva_project.load_package_seed('nyu-ed-classification', nyu_ed_classification.get_nyu_ed_classification_package_version(), 'ed_classification__johnston_icd10.csv.gz') }}"
        ed_classification__johnston_icd9:
          +post-hook: "{{ the_tuva_project.load_package_seed('nyu-ed-classification', nyu_ed_classification.get_nyu_ed_classification_package_version(), 'ed_classification__johnston_icd9.csv.gz') }}"
